//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomskiDezurstvo.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class RasporedSale
    {
        public int Id { get; set; }
        public int RasporedID { get; set; }
        public int SalaID { get; set; }

        [JsonIgnore]
        public virtual Raspored Raspored { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
