//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomskiDezurstvo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewUkupanBrojDezurstva
    {
        public int AsistentID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public Nullable<int> UkupanBrojDezurstva { get; set; }
    }
}
